# Generated by Django 2.1.3 on 2018-12-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
                ('category_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('product_price', models.IntegerField(default=100)),
                ('product_description', models.CharField(max_length=500)),
                ('product_rating', models.IntegerField(default=5)),
                ('product_quantity', models.IntegerField(default=10)),
                ('Category_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
