# Generated by Django 2.1.3 on 2018-12-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('postalcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User_Card_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_credit_card', models.IntegerField(unique=True)),
                ('user_credit_card_expiry_month', models.IntegerField()),
                ('user_credit_card_expiry_year', models.IntegerField()),
                ('user_debit_card', models.IntegerField(unique=True)),
                ('user_debit_card_expiry_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Credential',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_mobile', models.IntegerField(unique=True)),
                ('user_register_date', models.DateTimeField(auto_now_add=True)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User_Address')),
            ],
        ),
        migrations.CreateModel(
            name='User_Login_Logout_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_logout_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User_Credential')),
            ],
        ),
        migrations.CreateModel(
            name='User_Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User_Credential')),
            ],
        ),
        migrations.AddField(
            model_name='user_card_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User_Credential'),
        ),
    ]
